/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sorted_billing;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import static java.util.Collections.singleton;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class Adminsignup extends javax.swing.JFrame {
    static String gender;
    /**
     * Creates new form Adminsignup
     */
    public Adminsignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        pno = new javax.swing.JTextField();
        eid = new javax.swing.JTextField();
        conpass = new javax.swing.JPasswordField();
        setpass = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setText("Admin Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 20, 194, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel2.setText("First Name*");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(128, 75, 89, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(128, 109, 89, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel4.setText("Email Address*");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(102, 177, 110, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel5.setText("Set Passcode*");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(105, 212, 100, 18);

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel6.setText("Confirm Passcode*");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(74, 246, 130, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel7.setText("Phone No.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(128, 143, 89, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(253, 75, 223, 22);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(253, 109, 223, 22);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(253, 143, 223, 22);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(253, 177, 223, 22);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(253, 211, 223, 22);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(253, 246, 223, 22);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(510, 70, 180, 190);

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setText("Confirm");
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 300, 90, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(475, 0, 0, 317);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Register Admin");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(370, 10, 650, 70);

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel10.setText("First Name*");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(60, 120, 80, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel11.setText("Last Name");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(60, 200, 70, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel12.setText("Phone No.");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(60, 280, 80, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel13.setText("Email ID*");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(70, 360, 70, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel14.setText("Set Passcode*");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(50, 430, 100, 20);

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel15.setText("Confirm Passcode*");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(30, 530, 130, 20);
        jPanel2.add(fname);
        fname.setBounds(210, 112, 650, 30);

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        jPanel2.add(lname);
        lname.setBounds(210, 190, 650, 30);
        jPanel2.add(pno);
        pno.setBounds(210, 272, 660, 30);

        eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidActionPerformed(evt);
            }
        });
        jPanel2.add(eid);
        eid.setBounds(210, 352, 670, 30);

        conpass.setText("jPasswordField3");
        jPanel2.add(conpass);
        conpass.setBounds(210, 520, 670, 30);
        jPanel2.add(setpass);
        setpass.setBounds(210, 432, 670, 30);

        jButton2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jButton2.setText("Confirm");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(530, 672, 110, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adi.png"))); // NOI18N
        jPanel2.add(jLabel16);
        jLabel16.setBounds(1030, 220, 230, 250);

        male.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel2.add(male);
        male.setBounds(220, 610, 49, 20);

        female.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel2.add(female);
        female.setBounds(360, 610, 70, 20);

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel17.setText("Gender*");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(90, 610, 60, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void eidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eidActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(fname.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter Your first Name");
        }
        else if(eid.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter your email"); 
        }
        else if(setpass.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"confirm your passcode"); 
        }
        
        else if(conpass.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"enter confirm passcode"); 
        } else if(conpass.getText() .equals(setpass.getText()) == false)
                {
                JOptionPane.showMessageDialog(rootPane,"wrong confirm passcode");
                //continue;
                
        } else {
            String INSERTDB="INSERT INTO signUp(fname, lname, phoneno, email, gender, pass) VALUES(?,?,?,?,?,?)";
            try{
                PreparedStatement ps=com.mycompany.sorted_billing.ConnectionClass.getInstance().connection.prepareStatement(INSERTDB);
                ps.setString(1, fname.getText().toString());
                
                ps.setString(2, lname.getText().toString());
                ps.setString(3, pno.getText().toString());
                ps.setString(4, eid.getText().toString());
                
                if(male.isSelected()){
                    gender = "Male";
                }
                else{
                    gender="Female";
                }
                ps.setString(5,gender.toString());
                ps.setString(6, setpass.getText().toString());
               // ps.setString(5,selectedValue.toString());
                Boolean admin;
                admin = ps.execute();
                //for(int i=0;i<=100;i++)
                //{
                    conpass.getText();
                
                //}
               // else{
                 //       JOptionPane.showMessageDialog(rootPane,"wrong passcode");
                   // }
            } catch (SQLException ex) {
                Logger.getLogger(Adminsignup.class.getName()).log(Level.SEVERE, null, ex);
            }
             onetime oot=new onetime();
                    oot.setVisible(true);
                    this.dispose();
            
                
          //  }catch(SQLException sqlException){
            //    System.out.println("Error Message"+sqlException.getMessage());
            }
           /* DonorActivity donoractivity = new DonorActivity();
            donoractivity.setVisible(true);
            this.dispose();*/
         //  else{
           // JOptionPane.showMessageDialog(rootPane,"Enter Your gender");
        //}
           
        
        
        /*onetime ot=new onetime();
       ot.setVisible(true);
       this.dispose();
        */
    }//GEN-LAST:event_jButton2ActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
            onetime oot=new onetime();
                    oot.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminsignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField conpass;
    private javax.swing.JTextField eid;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField pno;
    private javax.swing.JTextField setpass;
    // End of variables declaration//GEN-END:variables
}
