/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sorted_billing;

import static com.mycompany.sorted_billing.Adminsignup.gender;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author HP
 */
public class emplo extends javax.swing.JInternalFrame {

    /**
     * Creates new form emplo
     */
    public emplo() {
        initComponents();
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        phno = new javax.swing.JTextField();
        eid = new javax.swing.JTextField();
        sid = new javax.swing.JTextField();
        setpass = new javax.swing.JPasswordField();
        conpass = new javax.swing.JPasswordField();
        sal = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        confirm = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(1236, 668));
        setPreferredSize(new java.awt.Dimension(1236, 668));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1236, 668));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("REGISTER EMPLOYEE");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(300, 30, 510, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("First Name*");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(110, 110, 90, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Last Name*");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(110, 160, 90, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Phone No*");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(110, 210, 80, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Email ID*");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(120, 260, 70, 30);
        jPanel2.add(jLabel6);
        jLabel6.setBounds(70, 220, 0, 0);

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("Set Passcode*");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(90, 360, 100, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 204));
        jLabel8.setText("Confirm Passcode*");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(60, 410, 130, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 204));
        jLabel9.setText("Salary*");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(130, 460, 50, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 204));
        jLabel10.setText("Gender*");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(130, 550, 60, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 204));
        jLabel11.setText("Store ID*");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(120, 310, 70, 30);

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel2.add(fname);
        fname.setBounds(220, 110, 670, 30);

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        jPanel2.add(lname);
        lname.setBounds(220, 160, 670, 30);
        jPanel2.add(phno);
        phno.setBounds(220, 210, 670, 30);
        jPanel2.add(eid);
        eid.setBounds(220, 260, 670, 30);
        jPanel2.add(sid);
        sid.setBounds(220, 310, 670, 30);
        jPanel2.add(setpass);
        setpass.setBounds(220, 360, 670, 30);
        jPanel2.add(conpass);
        conpass.setBounds(220, 410, 670, 30);
        jPanel2.add(sal);
        sal.setBounds(220, 460, 670, 30);

        male.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        male.setForeground(new java.awt.Color(204, 255, 255));
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel2.add(male);
        male.setBounds(240, 550, 60, 20);

        female.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        female.setForeground(new java.awt.Color(255, 204, 204));
        female.setText("Female");
        jPanel2.add(female);
        female.setBounds(360, 550, 70, 20);

        confirm.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        jPanel2.add(confirm);
        confirm.setBounds(780, 540, 100, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new1.PNG"))); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 0, 1200, 630);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1200, 668);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
       
         String regex = "^(?=.{1,64}@)[\\p{L}0-9_-]+(\\.[\\p{L}0-9_-]+)*@" 
        + "[^-][\\p{L}0-9-]+(\\.[\\p{L}0-9-]+)*(\\.[\\p{L}]{2,})$";
         Pattern pattern = Pattern.compile(regex); 
        Matcher matcher = pattern.matcher(eid.getText());  
        String stringRE = "^[\\p{L} .'-]+$"; 
         Pattern stringPattern = Pattern.compile(stringRE);
          Matcher firstMatcher = stringPattern.matcher(fname.getText()); 
          Matcher lastMatcher = stringPattern.matcher(lname.getText());
          
          String phoneRE = "[0-9]+";
         Pattern phonePattern = Pattern.compile(phoneRE);
          Matcher phoneMatcher = phonePattern.matcher(phno.getText());
          String salaryRE = "[0-9]+";
         Pattern salaryPattern = Pattern.compile(salaryRE);
          Matcher salaryMatcher = salaryPattern.matcher(sal.getText());
          
        if(fname.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter first Name");
        }
        else if(firstMatcher.matches()==false)
        {
            JOptionPane.showMessageDialog(rootPane,"Enter first name with only alphabets"); 
        }
        else if(lname.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter last Name");
        }
        else if(lastMatcher.matches()==false)
        {
            JOptionPane.showMessageDialog(rootPane,"Enter last name with only alphabets"); 
        }
        else if(phno.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane,"Enter phone number");
            
        }
        else if(phoneMatcher.matches()==false)
        {
            JOptionPane.showMessageDialog(rootPane,"Enter digits only"); 
        }
        else if(phno.getText().length()!=10)
        {
            JOptionPane.showMessageDialog(rootPane,"Enter valid phone number");
        }
        else if(eid.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter email"); 
        }
        else if(matcher.matches()==false)
           {
                JOptionPane.showMessageDialog(rootPane,"Enter valid email");
           }
        
         else if(sid.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter store ID"); 
        }
        else if(setpass.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"confirm your passcode"); 
        }
        
        else if(sal.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"enter salary"); 
        }
        else if(salaryMatcher.matches()==false)
        {
            JOptionPane.showMessageDialog(rootPane,"Enter digits only"); 
        }
        
        else if(conpass.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"enter confirm passcode"); 
        } else if(conpass.getText() .equals(setpass.getText()) == false)
                {
                JOptionPane.showMessageDialog(rootPane,"wrong confirm passcode");
                //continue;
                
        } else {
            String INSERTDB="INSERT INTO signUpemp(fname, lname, phoneno, email, storeID, salary, gender, pass) VALUES(?,?,?,?,?,?,?,?)";
            try{
                PreparedStatement ps=com.mycompany.sorted_billing.ConnectionClass.getInstance().connection.prepareStatement(INSERTDB);
                ps.setString(1, fname.getText().toString());
                
                ps.setString(2, lname.getText().toString());
                ps.setString(3, phno.getText().toString());
                ps.setString(4, eid.getText().toString());
                ps.setString(5, sid.getText().toString());
                ps.setString(6, sal.getText().toString());
                
                if(male.isSelected()){
                    gender = "Male";
                }
                else{
                    gender="Female";
                }
                ps.setString(7,gender.toString());
                ps.setString(8, setpass.getText().toString());
               // ps.setString(5,selectedValue.toString());
                Boolean admin;
                admin = ps.execute();
                //for(int i=0;i<=100;i++)
                //{
                    conpass.getText();
                
                //}
               // else{
                 //       JOptionPane.showMessageDialog(rootPane,"wrong passcode");
                   // }
            } catch (SQLException ex) {
                Logger.getLogger(emplo.class.getName()).log(Level.SEVERE, null, ex);
            }
             onetime oot=new onetime();
                    oot.setVisible(true);
                    this.dispose();
        }
        
    }//GEN-LAST:event_confirmActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private javax.swing.JPasswordField conpass;
    private javax.swing.JTextField eid;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField phno;
    private javax.swing.JTextField sal;
    private javax.swing.JPasswordField setpass;
    private javax.swing.JTextField sid;
    // End of variables declaration//GEN-END:variables
}
