/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sorted_billing;
import java.awt.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import com.mycompany.sorted_billing.EmployeeModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import com.mycompany.sorted_billing.employeeLogin;

/**
 *
 * @author Hp
 */
public class EMPScreen extends javax.swing.JFrame implements EMPScreenInterface {
 ArrayList<EmployeeModel> list = new ArrayList<EmployeeModel>();
    /**
     * Creates new form EMPScreen
     */
 
 inventory1 inv;
 bill bill;
 home home;
 additems items;
    Color defaultcolor,clickedcolor;
    public String store;
    public EMPScreen() {
        setUpView();
    }
    
    public EMPScreen(String sid) {
        store = sid;    
        setUpView();
    }
    
    public void setUpView() {
        initComponents();
        defaultcolor = new Color(67,151,211);
        clickedcolor = new Color(255,0,0);
        exit.setBackground(defaultcolor);
        homeButton.setBackground(defaultcolor);
        inventory.setBackground(defaultcolor);
        bills.setBackground(defaultcolor);
        storeid.setText(store);
        getEmployees();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        storeid = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        stname = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        bills = new javax.swing.JButton();
        inventory = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        inve = new javax.swing.JDesktopPane();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(67, 150, 210));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMP ID");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 10, 70, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMP Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 50, 100, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(1140, 40, 50, 20);

        storeid.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        storeid.setForeground(new java.awt.Color(255, 255, 255));
        storeid.setText("ID Of EMPLOYEE");
        storeid.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                storeidComponentShown(evt);
            }
        });
        jPanel2.add(storeid);
        storeid.setBounds(130, 10, 150, 20);

        name.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("NAME OF EMPLOYEE");
        name.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                nameComponentShown(evt);
            }
        });
        jPanel2.add(name);
        name.setBounds(130, 50, 140, 19);

        stname.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        stname.setForeground(new java.awt.Color(255, 51, 51));
        stname.setText("NAME OF STORE");
        jPanel2.add(stname);
        stname.setBounds(410, 20, 400, 50);

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PRESENT DATE");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(1210, 40, 120, 19);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pleiades_large.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(-40, 0, 1410, 90);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1370, 90);

        jPanel4.setBackground(new java.awt.Color(67, 150, 210));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel4.setMaximumSize(new java.awt.Dimension(130, 768));
        jPanel4.setMinimumSize(new java.awt.Dimension(130, 768));
        jPanel4.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel7.setText("Date");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(520, 0, 50, 25);

        exit.setBackground(new java.awt.Color(67, 151, 211));
        exit.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        exit.setText("exit");
        exit.setBorder(null);
        exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                exitMouseMoved(evt);
            }
        });
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel4.add(exit);
        exit.setBounds(0, 380, 130, 50);

        bills.setBackground(new java.awt.Color(67, 151, 211));
        bills.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        bills.setText("Billing");
        bills.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billsMouseClicked(evt);
            }
        });
        bills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billsActionPerformed(evt);
            }
        });
        jPanel4.add(bills);
        bills.setBounds(0, 290, 130, 50);

        inventory.setBackground(new java.awt.Color(67, 151, 211));
        inventory.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        inventory.setText("Inventory");
        inventory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryMouseClicked(evt);
            }
        });
        inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryActionPerformed(evt);
            }
        });
        jPanel4.add(inventory);
        inventory.setBounds(0, 200, 130, 50);

        homeButton.setBackground(new java.awt.Color(67, 151, 211));
        homeButton.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        homeButton.setText("Home");
        homeButton.setBorder(null);
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
        });
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel4.add(homeButton);
        homeButton.setBounds(0, 110, 130, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pleiades_large.jpg"))); // NOI18N
        jLabel4.setMinimumSize(new java.awt.Dimension(130, 768));
        jPanel4.add(jLabel4);
        jLabel4.setBounds(0, 20, 130, 900);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 70, 130, 1300);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpeg"))); // NOI18N
        inve.add(jLabel6);
        jLabel6.setBounds(390, 140, 370, 250);

        jPanel1.add(inve);
        inve.setBounds(130, 90, 1240, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryActionPerformed

    private void billsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billsActionPerformed

    private void inventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseClicked
       inv = new inventory1();
       removeAllInternalFrames();
       inve.add(inv).setVisible(true);
    }//GEN-LAST:event_inventoryMouseClicked

    private void billsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsMouseClicked
        // TODO add your handling code here:
        bill=new bill(this);
        removeAllInternalFrames();
        inve.add(bill).setVisible(true);
    }//GEN-LAST:event_billsMouseClicked

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
           this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
  
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_exitMouseMoved

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeButtonActionPerformed

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        // TODO add your handling code here:
          home =new home();
    removeAllInternalFrames();
    inve.add(home).setVisible(true);
    
    }//GEN-LAST:event_homeButtonMouseClicked

    private void nameComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_nameComponentShown
        // TODO add your handling code here:
      name.setText(store);        
    }//GEN-LAST:event_nameComponentShown

    private void storeidComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_storeidComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_storeidComponentShown
void getEmployees() {
    final String statement = "SELECT * from signUpemp where storeid=?";
         try {
            PreparedStatement preparedStatement = ConnectionClass.getInstance().connection.prepareStatement(statement);
            preparedStatement.setString(1, store);
            ResultSet resultSet = preparedStatement.executeQuery();
            list.clear();
            

            while (resultSet.next()) {
                    
                EmployeeModel employeeModel = new EmployeeModel();
                employeeModel.setStoreID(resultSet.getString("storeID"));
                employeeModel.setFirstName(resultSet.getString("fname"));
                employeeModel.setLastName(resultSet.getString("lname"));
                employeeModel.setPhonenNo(resultSet.getString("phoneno"));
                employeeModel.setSalary(resultSet.getString("salary"));
                employeeModel.setEmail(resultSet.getString("email"));
                employeeModel.setGender(resultSet.getString("gender"));
                employeeModel.setId(resultSet.getInt("id"));
                
                name.setText(employeeModel.getFirstName());
               
                list.add(employeeModel);
            }
            
                
            for (EmployeeModel employeeModel: list) {
                
//                System.out.println(userModel.getEmail());
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ViewEmployeesJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EMPScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EMPScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EMPScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EMPScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EMPScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bills;
    private javax.swing.JButton exit;
    private javax.swing.JButton homeButton;
    private javax.swing.JDesktopPane inve;
    private javax.swing.JButton inventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel name;
    private javax.swing.JLabel stname;
    private javax.swing.JLabel storeid;
    // End of variables declaration//GEN-END:variables

    private void removeAllInternalFrames() {
        if (inv != null) {
            inv.dispose();
        }
        if (bill != null){
            bill.dispose();
        }
        if (home != null) {
            home.dispose();
        }
        inve.removeAll();
    }
    @Override
    public void nextButtonOnBillingScreenPressed() {
        //open enxt frame
        System.out.println("HAHAHHAHAHAHAH");
        items=new additems();
        inve.add(items).setVisible(true);
    }
}
