/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sorted_billing;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import com.mycompany.sorted_billing.EmployeeModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author HP
 */
public class inventory2 extends javax.swing.JInternalFrame {
    ArrayList<inventoryModel> list = new ArrayList<inventoryModel>();
    /**
     * Creates new form inventory2
     */
//    InventoryInterface inventory;
    public void setupview() {
        
        initComponents();
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        inventory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        invbox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        invtable = new javax.swing.JTable();
        check = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1236, 668));
        setPreferredSize(new java.awt.Dimension(1236, 668));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 51, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setText("catagory");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 110, 80, 40);

        invbox.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.add(invbox);
        invbox.setBounds(200, 112, 180, 30);

        invtable.setBackground(new java.awt.Color(204, 255, 204));
        invtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Items", "Qty", "price(per)"
            }
        ));
        jScrollPane1.setViewportView(invtable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(400, 80, 790, 402);

        check.setBackground(new java.awt.Color(255, 255, 204));
        check.setText("check");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jPanel1.add(check);
        check.setBounds(160, 200, 100, 22);

        add.setText("add");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(160, 270, 100, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blende.PNG"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1220, 631);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1230, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents
void inventory(){
final String statement = "SELECT * from inventory";
        try {
            PreparedStatement preparedStatement = ConnectionClass.getInstance().connection.prepareStatement(statement);
            ResultSet resultSet = preparedStatement.executeQuery();
            list.clear();
            invbox.removeAllItems();

            while (resultSet.next()) {
                    
                inventoryModel invModel = new inventoryModel();
                invModel.setID(resultSet.getInt("id"));
                invModel.setCatagory(resultSet.getString("Catagory"));
                invModel.setItem(resultSet.getString("item"));
                invModel.setQty(resultSet.getString("Qty"));
                invModel.setPrice(resultSet.getString("price"));
                list.add(invModel);
                invbox.addItem(invModel.getCatagory());
                }
            for (inventoryModel employeeModel: list) {
                  invbox.addItem(employeeModel.getCatagory());
//                System.out.println(userModel.getEmail())
            }
                
            
            
        } catch (SQLException ex) {
            Logger.getLogger(inventory2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
       final String statement = "SELECT * from inventory";

        try {
            PreparedStatement preparedStatement = ConnectionClass.getInstance().connection.prepareStatement(statement);
                inventoryModel invModel = new inventoryModel();

            ResultSet resultSet = preparedStatement.executeQuery();
            final String[] headerName = {"items","Qty", "Price(per)"};
            DefaultTableModel tableModel = new DefaultTableModel(null, headerName);
            invtable.setModel(tableModel);
            Object[] row = new Object[3];


            list.clear();

            while (resultSet.next()) {
                    
//                UserModel userModel = new UserModel();
                invModel.setItem(resultSet.getString("item"));
                invModel.setQty(resultSet.getString("Qty"));
                invModel.setPrice(resultSet.getString("price"));
                
                list.add(invModel);
                
                row[0] = invModel.getItem();
                row[1] = invModel.getQty();
                row[2] = invModel.getPrice();
                tableModel.addRow(row);
            }
                
            for (inventoryModel userModel: list) {
                System.out.println(userModel.getCatagory());
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(inventory2.class.getName()).log(Level.SEVERE, null, ex);
        }

         final inventoryModel selectedCategory = list.get(invbox.getSelectedIndex());
          DefaultTableModel dtm = (DefaultTableModel) invtable.getModel();
        int selectedRow = invtable.getSelectedRow();
        
        //UserModel userModel = new UserModel();
        
        for (inventoryModel listElement: list) {
            if (listElement.getCatagory().equals(invbox.getSelectedIndex())) {
                
                break;
            }
        }
        

       
    }//GEN-LAST:event_checkActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
//        this.inventory.addbuttonclicked();
    }//GEN-LAST:event_addActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        additems ad=new additems();
       removeAll();
       add(ad).setVisible(true);
    }//GEN-LAST:event_addMouseClicked
 public inventory2(InventoryInterface inventory) {
//        this.inventory = inventory;
        
    }
 public inventory2() {
        setupview();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton check;
    private javax.swing.JComboBox<String> invbox;
    private javax.swing.JTable invtable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
