/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sorted_billing;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class storeregd extends javax.swing.JFrame {

    ConnectionClass connection;
    /**
     * Creates new form NewJFrame
     */
    public storeregd() throws SQLException {
        this.connection = ConnectionClass.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        store = new javax.swing.JComboBox<>();
        next = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 0));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        jLabel4.setText("Sorted Billing");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(35, 15, 331, 55);

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel1.setText("Enter Store Name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 110, 234, 32);

        name.setBackground(new java.awt.Color(204, 255, 255));
        name.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jPanel2.add(name);
        name.setBounds(180, 180, 470, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel2.setText("Type of Store");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 240, 201, 30);

        store.setBackground(new java.awt.Color(204, 255, 255));
        store.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        store.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Chemist", "Stationary Store", "Grocery Store", "Cosmetic Store", "Convenience Store", "Garment Store", "Confectionary Store", "Farm", " " }));
        store.setMinimumSize(new java.awt.Dimension(64, 22));
        store.setPreferredSize(new java.awt.Dimension(64, 22));
        jPanel2.add(store);
        store.setBounds(180, 310, 480, 40);

        next.setBackground(new java.awt.Color(153, 255, 102));
        next.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        next.setText("Get Started");
        next.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel2.add(next);
        next.setBounds(970, 370, 150, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bil.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(940, 110, 210, 250);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
if(name.getText().isEmpty())
{
JOptionPane.showMessageDialog(rootPane,"store name can not be empty");
}// TODO add your handling code here:
if(store.getSelectedItem()== null)
{
JOptionPane.showMessageDialog(rootPane,"enter store type");
}
Adminsignup adi =new Adminsignup();
adi.setVisible(true);
this.dispose();
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(storeregd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(storeregd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(storeregd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(storeregd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new storeregd().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(storeregd.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JButton next;
    private javax.swing.JComboBox<String> store;
    // End of variables declaration//GEN-END:variables
}
