package com.mycompany.sorted_billing;

//import com.mycompany.sorted_billing.adminscreeninterface;
//import adminscreeninterface;
//import adminscreeninterface;
//import adminscreeninterface;
//import adminscreeninterface;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import com.mycompany.sorted_billing.EmployeeModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class ViewEmployeesJFrame extends javax.swing.JInternalFrame{
 adminscreeninterface adminscreen;
    ArrayList<EmployeeModel> list = new ArrayList<EmployeeModel>();
    /**
     * Creates new form NewJInternalFrame
     */ 
    
    public ViewEmployeesJFrame() {
        setUpView();
    }
    
    public ViewEmployeesJFrame(adminscreeninterface adminscreen) {
        this.adminscreen = adminscreen;
        setUpView();
    }
    
    public void setUpView(){
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        getEmployees();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ecbox = new javax.swing.JComboBox<>();
        seede = new javax.swing.JButton();
        employeefNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emplastname = new javax.swing.JLabel();
        empphoneno = new javax.swing.JLabel();
        empemail = new javax.swing.JLabel();
        storeid = new javax.swing.JLabel();
        salary = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        addemp = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(1236, 668));
        setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1236, 668));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setMinimumSize(new java.awt.Dimension(1230, 668));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee name ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 120, 120, 40);

        ecbox.setBackground(new java.awt.Color(204, 0, 255));
        ecbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ecbox.setMinimumSize(new java.awt.Dimension(1236, 668));
        ecbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecboxActionPerformed(evt);
            }
        });
        jPanel2.add(ecbox);
        ecbox.setBounds(220, 122, 170, 30);

        seede.setBackground(new java.awt.Color(204, 0, 255));
        seede.setText("see details");
        seede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seedeMouseClicked(evt);
            }
        });
        seede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seedeActionPerformed(evt);
            }
        });
        jPanel2.add(seede);
        seede.setBounds(160, 190, 100, 30);

        employeefNameLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        employeefNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        employeefNameLabel.setText("fname");
        jPanel2.add(employeefNameLabel);
        employeefNameLabel.setBounds(670, 120, 290, 30);

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("first name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(537, 120, 100, 30);

        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("last name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(540, 176, 100, 30);

        jLabel4.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("phone no");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(540, 230, 100, 30);

        jLabel5.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("email id");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(550, 280, 90, 30);

        jLabel6.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Store id");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(550, 330, 90, 30);

        jLabel7.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("salary");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(560, 390, 60, 30);

        jLabel8.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("gender");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(560, 440, 70, 30);

        emplastname.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        emplastname.setForeground(new java.awt.Color(255, 255, 255));
        emplastname.setText("lname");
        jPanel2.add(emplastname);
        emplastname.setBounds(670, 180, 290, 30);

        empphoneno.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        empphoneno.setForeground(new java.awt.Color(255, 255, 255));
        empphoneno.setText("phone no");
        jPanel2.add(empphoneno);
        empphoneno.setBounds(670, 230, 270, 30);

        empemail.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        empemail.setForeground(new java.awt.Color(255, 255, 255));
        empemail.setText("email");
        jPanel2.add(empemail);
        empemail.setBounds(670, 280, 280, 30);

        storeid.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        storeid.setForeground(new java.awt.Color(255, 255, 255));
        storeid.setText("store id");
        jPanel2.add(storeid);
        storeid.setBounds(670, 330, 150, 30);

        salary.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        salary.setForeground(new java.awt.Color(255, 255, 255));
        salary.setText("salary");
        jPanel2.add(salary);
        salary.setBounds(670, 390, 110, 30);

        gender.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setText("gender");
        jPanel2.add(gender);
        gender.setBounds(670, 440, 80, 30);

        addemp.setBackground(new java.awt.Color(204, 0, 255));
        addemp.setText("add employee");
        addemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addempActionPerformed(evt);
            }
        });
        jPanel2.add(addemp);
        addemp.setBounds(150, 260, 110, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smoke.PNG"))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 0, 1220, 630);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1230, 668);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void getEmployees() {
        final String statement = "SELECT * from signUpemp";
        try {
            PreparedStatement preparedStatement = ConnectionClass.getInstance().connection.prepareStatement(statement);
            ResultSet resultSet = preparedStatement.executeQuery();
            list.clear();
            ecbox.removeAllItems();

            while (resultSet.next()) {
                    
                EmployeeModel employeeModel = new EmployeeModel();
                employeeModel.setStoreID(resultSet.getString("storeID"));
                employeeModel.setFirstName(resultSet.getString("fname"));
                employeeModel.setLastName(resultSet.getString("lname"));
                employeeModel.setPhonenNo(resultSet.getString("phoneno"));
                employeeModel.setSalary(resultSet.getString("salary"));
                employeeModel.setEmail(resultSet.getString("email"));
                employeeModel.setGender(resultSet.getString("gender"));
                employeeModel.setId(resultSet.getInt("id"));
                list.add(employeeModel);
                ecbox.addItem(employeeModel.getFirstName());
                
                
            }
            
                
            for (EmployeeModel employeeModel: list) {
                  ecbox.addItem(employeeModel.getFirstName());
//                System.out.println(userModel.getEmail())
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ViewEmployeesJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    private void ecboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecboxActionPerformed

    private void seedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seedeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_seedeMouseClicked

    private void seedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seedeActionPerformed
        final EmployeeModel selectedEmployee = list.get(ecbox.getSelectedIndex());
        employeefNameLabel.setText(selectedEmployee.getFirstName());
        emplastname.setText(selectedEmployee.getLastName());
        empphoneno.setText(selectedEmployee.getPhonenNo());
        empemail.setText(selectedEmployee.getEmail());
        storeid.setText(selectedEmployee.getStoreID());
        salary.setText(selectedEmployee.getSalary());
        gender.setText(selectedEmployee.getGender());
    }//GEN-LAST:event_seedeActionPerformed

    
   
    private void addempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addempActionPerformed
        // TODO add your handling code here:
                this.adminscreen.nextButtonOnaddempPressed();

    }//GEN-LAST:event_addempActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addemp;
    private javax.swing.JComboBox<String> ecbox;
    private javax.swing.JLabel empemail;
    private javax.swing.JLabel emplastname;
    private javax.swing.JLabel employeefNameLabel;
    private javax.swing.JLabel empphoneno;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel salary;
    private javax.swing.JButton seede;
    private javax.swing.JLabel storeid;
    // End of variables declaration//GEN-END:variables

}